package com.ios.testhelper.kpitests.enums;

/**
 * Created by avsupport on 3/5/14.
 */
public enum  ConfigurationParametersEnum {
    DATE_FIELD_NAME,
    TIME_FIELD_NAME,
    BUILD_FIELD_NAME,
    HW_FIELD_NAME,
    OS_FIELD_NAME,
    NET_FIELD_NAME,
    DEVICE_ID_FIELD_NAME,
    SLAVE_ID_FIELD_NAME,
    TEST_TYPE_FIELD_NAME,
    TEST_ID_FIELD_NAME,
    TEST_NAME_FIELD_NAME,
    TEST_ACTION_FIELD_NAME,
    TEST_DATA_FIELD_NAME,
    USED_MEMORY_FIELD_NAME,
    START_TIME_FIELD_NAME,
    END_TIME_FIELD_NAME,
    TOTAL_TIME_FIELD_NAME,
    TEST_RESULT_FIELD_NAME,
    TEST_CYCLE_FIELD_NAME,

    BUILD_PATH,
    PATH_RESULT_FOLDER,
    DEVICE_ID,

    DUMP_KPI_INFO,
    LOGIN,
    PASSWORD,
    TIMEOUT,

    DRP_MAGAZINE,
    DRP_DOWNLOAD_TIMEOUT,

    WOODWIN_MAGAZINE,
    WOODWIN_DOWNLOAD_TIMEOUT,

    DRP_COMICS,
    COMICS_DOWNLOAD_TIMEOUT,

    BOOK,
    BOOK_DOWNLOAD_TIMEOUT,

    PDF,
    PDF_DOWNLOAD_TIMEOUT,

    SAMPLE_DOWNLOAD_TIMEOUT
}
